{% set name = "harlequin-postgres" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/harlequin_postgres-{{ version }}.tar.gz
  sha256: d7fb402e4639c33f6539673642c66411afeac740f18ca22255f5d37cebb8c101

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - psycopg >=3.2.0,<4.0.0
    - psycopg-pool >=3.2.2,<4.0.0
    - python >=3.8.1,<4.0
    - harlequin >=1.20,<3
    - psycopg2-binary >=2.9.9,<3.0.0

test:
  imports:
    - harlequin_postgres
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tconbeer/harlequin-postgres
  summary: A Harlequin adapter for Postgres.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/harlequin
