{% set name = "harlequin-postgres" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/harlequin_postgres-{{ version }}.tar.gz
  sha256: 5e9e863170dcf4a8c7f194a30ae7e3c791226371fd08a9779c5bcff432d1d69d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - psycopg >=3.2.0,<4.0.0
    - psycopg-pool >=3.2.2,<4.0.0
    - python >={{ python_min }},<4.0
    - harlequin >=1.25,<3
    - psycopg2-binary >=2.9.9,<3.0.0

test:
  imports:
    - harlequin_postgres
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tconbeer/harlequin-postgres
  summary: A Harlequin adapter for Postgres.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/harlequin
