{% set name = "harlequin-postgres" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/harlequin_postgres-{{ version }}.tar.gz
  sha256: 205f2e7aa623c1a1bd2354b8fa1d38b33e2962923183168586ca4688fb1acb81

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8.1,<4.0
    - harlequin >=1.7.0,<2.0.0
    - psycopg2-binary >=2.9.9,<3.0.0

test:
  imports:
    - harlequin_postgres
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tconbeer/harlequin-postgres
  summary: A Harlequin adapter for Postgres.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/harlequin
