{% set name = "harlequin-postgres" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/harlequin_postgres-{{ version }}.tar.gz
  sha256: cc1b5582a05459a56339d7165c05f32466afb50f4eef18074331b0d0c38e9c15

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8.1,<4.0
    - harlequin >=1.20.0,<2.0.0
    - psycopg2-binary >=2.9.9,<3.0.0

test:
  imports:
    - harlequin_postgres
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tconbeer/harlequin-postgres
  summary: A Harlequin adapter for Postgres.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/harlequin
