schema_version: 1

context:
  name: harlequin-postgres
  version: 1.3.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/harlequin_postgres-${{ version }}.tar.gz
  sha256: 25dcb73e97cdfb17c3bcfdc3146418a98ff11ce68f6a51fb1b25322eac9d5223

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - psycopg-pool
    - psycopg >=3.2,<4
    - harlequin >=1.25,<3
tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - harlequin_postgres

about:
  summary: A Harlequin adapter for Postgres.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/tconbeer/harlequin-postgres

extra:
  recipe-maintainers:
    - conda-forge/harlequin
