schema_version: 1

context:
  name: harlequin-postgres
  version: 1.4.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/harlequin_postgres-${{ version }}.tar.gz
  sha256: e352c74312752f279aa33bf97284e322ef1447f18595b0b583265ad843df7bab

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - psycopg >=3.2,<4
    - harlequin >=2.11,<3
tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - harlequin_postgres

about:
  summary: A Harlequin adapter for Postgres.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/tconbeer/harlequin-postgres

extra:
  recipe-maintainers:
    - conda-forge/harlequin
